version: "3"

tasks:
  test:
    desc: Run all tests without logs
    cmds:
      - GORM_SILENT=true go test ./tests/...

  test:loud:
    desc: Run all tests
    cmds:
      - go test ./tests/... -v

  test:failures:
    desc: Run all tests but only show failures
    cmds:
      - go test ./tests/... | grep -A 10 -B 2 FAIL

  test:coverage:
    desc: Run tests with coverage
    cmds:
      - go test -coverpkg=./src/... ./tests/... -coverprofile=coverage.out
      - go tool cover -func=coverage.out

  test:coverage:html:
    desc: Generate HTML coverage report and open it in a browser
    cmds:
      - go test -coverpkg=./src/... ./tests/... -coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html
      - open coverage.html

  dev:
    desc: Run the application
    cmds:
      - wails dev

  lint:
    desc: Run linters
    cmds:
      - go vet ./...
      - golangci-lint run ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f palm
      - rm -f palm.sqlite
      - rm -f coverage.out
      - rm -f coverage.html

  populate:emails:
    desc: Populate database with sample emails from fixtures
    cmds:
      - go run -mod=mod scripts/populate_emails.go
