// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controllers} from '../models';

export function GetEmail(arg1:number):Promise<controllers.EmailResponse>;

export function Greet(arg1:string):Promise<string>;

export function ListEmails(arg1:number,arg2:number,arg3:number):Promise<controllers.ListEmailsResponse>;
