// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEmail(arg1) {
  return window['go']['main']['App']['GetEmail'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListEmails(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListEmails'](arg1, arg2, arg3);
}
